// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// s2io
int s2io(Rcpp::NumericMatrix cc);
RcppExport SEXP _global_s2io(SEXP ccSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type cc(ccSEXP);
    rcpp_result_gen = Rcpp::wrap(s2io(cc));
    return rcpp_result_gen;
END_RCPP
}
// area_loops_from_list
Rcpp::NumericVector area_loops_from_list(Rcpp::List l);
RcppExport SEXP _global_area_loops_from_list(SEXP lSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type l(lSEXP);
    rcpp_result_gen = Rcpp::wrap(area_loops_from_list(l));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_global_s2io", (DL_FUNC) &_global_s2io, 1},
    {"_global_area_loops_from_list", (DL_FUNC) &_global_area_loops_from_list, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_global(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
