# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

s2io <- function(cc) {
    .Call('_global_s2io', PACKAGE = 'global', cc)
}

area_loops_from_list <- function(l) {
    .Call('_global_area_loops_from_list', PACKAGE = 'global', l)
}

